### ISSUE TITLE
Implement version 1

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/gws2xlsx#1]
Java command line program with the following options:

`-f`
GWS file. Exactly one of -f, -j or -d must be present.

`-d`
Folder with GWS files. Exactly one of -f, -j or -d must be present.

`-g`
GlyTouCan ID generation. At least one of -g or -c must be present.

`-c` 
Cartoon generation. At least one of -g or -c must be present.

`-o`
Output folder. Mandatory.

`-j`
Job file.  Exactly one of -f, -j or -d must be present.

**Program logic**
* Load the GWS sequences from the  GWS file (`-f`) or from multiple GWS files (`-d`). Or retrieve the last job dump with `-j`
* Generate the glycan cartoon (if `-c` is used)
* Retrieve the GlyTouCan IDs (if `-g` is used). If necessary register them. Store the status for each structure (was already in GlyTouCan, newly submitted for registration, newly registered). If the last status was "newly submitted for registration" and a `-j` rerun shows that it is now in GlyTouCan the status changes to "newly registered".
* Generate the Excel output in the output folder (see below)
* Serialize the job into a json file in the output folder

**Output**
Excel file with the following columns:
1. Name of the original GWS file (only if -d is used)
2. Number of the sequence in the GWS file
3. GlyTouCan ID (only if -g is not used)
4. Glycan Cartoon (only if -c is not used)

**Job File**
This file contains the last status of the current job. It has a list of input files. With each file having a list of glycans. Each glycan has a GWS sequences (other sequences such as GlycoCT and WURCS as needed), the last status from the GlyTouCan registration.

**Comment by senaarpinar** [comment]
add a column for errors into the excel sheet

**Comment by senaarpinar** [comment]
The first version is implemented
