### ISSUE TITLE
Fix the DGal1d1aldi problem

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/gws2xlsx#3]
Add the attached classes to the project. After converting from GWS to GlycoCT and BEFORE running the validation - run the code:

```
		RectifyGlycoCT t_rectifier = new RectifyGlycoCT();
		String t_glycoCTNew = t_rectifier.rectify(t_glycoCTfromGWS);
```

Than rerun Mindies first file (from JSON) and see if there are still validation errors.

[org.zip](https://github.com/glygener/gws2xlsx/files/10972651/org.zip)

**Comment by senaarpinar** [comment]
I added this code and there are no validation errors anymore.
