### ISSUE TITLE
Add more columns to the export file

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/gws2xlsx#4]
Add the following columns after the last column. All cells are empty only the column header is present (except see below):
* Paper
* Species
* Tissue
* Cell line ID
* Disease
* has_abundance
* has_expression
* Functional annotation/Keyword
* Glycan dictionary term ID
* Contributor

The cells for the following have the provided default values for each glycan:
* "has_abundance" : "no"
* "has_expression" : "no"
* "Contributor" : "createdBy:Mindy Porterfield(mindyp@ccrc.uga.edu, CCRC)"

**Comment by senaarpinar** [comment]
added the columns
