### ISSUE TITLE
Additional column

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/gws2xlsx#6]
This is related to #4. We need one more column in the end after contributor. The label is "Experimental technique" and its not prefilled.

**Comment by senaarpinar** [comment]
I added this column and uploaded the updated [spreadsheet](https://gwu0.sharepoint.com/:x:/r/sites/GlyGenTeam-GRP/_layouts/15/Doc.aspx?sourcedoc=%7B191B3BF6-C600-4EE9-B4AE-8B8D45F6402D%7D&file=Glycans-FriMar312023.xlsx&action=default&mobileredirect=true) to sharepoint
